config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[index new create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :update_comment
  after_destroy :update_comment

  def update_comment
    post.update(comments_counter: post.comments.count)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_user, only: %i[index create]
  before_action :find_post, only: %i[index create destroy]

  def index
    @comments = @post.comments
    render json: @comments
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments or /comments.json
  def create
    comment = Comment.new(comment_params)
    comment.author = current_user
    comment.post = @post

    respond_to do |format|
      if comment.save
        format.html { redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.' }
        format.json { render json: comment }
      else
        format.html { redirect_to user_post_path(@user, @post), notice: 'Comment was not successfully created.' }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    # find_post
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to user_post_path(@post.author, @post), notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      else
        redirect_to user_post_path(@post.author, @post), alert: 'Comment not deleted.'
      end
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%if false%>
<div id="<%= dom_id comment %>">
  <p>
    <strong>Author:</strong>
    <%= comment.author_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

</div>
<%end%>
<%############## DISPLAY COMMENTS #####################%>
<% if post.comments_counter == 0 %>
  <div class='comments'>
    <p>No comments yet!</p>
  </div>
<% end %>

<% if post.comments_counter > 0 %>
  <ul class='comments'>
    <% post.comments.each do |comment| %>
      <div class='comment'>
        <div><%= comment.author.name %>:</div>
        <div class='comment-box'><%= comment.text %></div>
        
        <%############## DELETE BUTTON COMMENT #####################%>
          <%= render 'shared/delete_btn', object: comment, path: user_post_comment_path(@user, post, comment) %>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url: user_post_comments_path) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='comments_form'>

 

   <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
   </div>

   <div>
    <%= form.submit %>
   </div>

   </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<div class='new_comment'>

 <h1>New comment</h1>

  <%= render "form", comment: @comment %>

  <br>

   <div>
       <%= link_to "Back to comments",  :back  %>
    </div>

</div>

app/views/comments/show.html.erb
<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>