config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[index new create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %i[user admin].freeze

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  # before_action :set_user, only: %i[show]

  # GET /users or /users.json
  def index
    @users = User.includes(:posts).order(updated_at: :asc)
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1 or /users/1.json
  def show
    # set_user
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :photo, :bio, :posts_counter)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :posts_counter, style: "display: block" %>
    <%= form.number_field :posts_counter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if false %> 
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= user.photo %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= user.bio %>
  </p>

  <p>
    <strong>Posts counter:</strong>
    <%= user.posts.count %>
  </p>
</div>
<%end%>


<%################### SHOW USER ##########################%>
  <ul id="<%= dom_id user %>">
    <li class='users_card'>
        <div class="photo">
          <img src="<%= user.photo %>" alt="<%= user.name %>">
        </div>
      <div class="frame">
        <div class="name_bio">
          <h2><%= link_to user.name, user %></h2>  
        </div>

        <div class='num_post'>
        <p>Number of posts(<%= user.posts.count %>)</p>
        <div>
        </div>
      </li>
  </ul>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<% if false %>
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%####################### NEW USER #################################%>
<%= link_to "New user", new_user_path %>
<% end %>
<h1 class='users_title'>Users</h1>
  <ul>
    <% @users.each do |user| %>
    <li class='users_card'>
        <div class="photo">
          <img src="<%= user.photo %>" alt="<%= user.name %>">
        </div>
       <div class="frame">
        <div class="name_bio">
          <h2><%= link_to user.name, user %></h2>  
        </div>



        <div class='num_post'>
        <p>Number of posts(<%= user.posts.count %>)</p>
        <div>
        </div>
      </li>
    <% end %>
  </ul>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%= render @user %>
<%##################### START USER FORM #######################%>
<div class='bio'>
    <h2>Bio</h2>
    <p><%= @user.bio %></p>
  </div>
  <%= render 'shared/open_post_form', user: @user %>
  <ul class='posts'>
    <% if @user.posts.empty? %>
      <li class='post border1'>This user has no posts yet!</li>
    <% end %>

    <% @user.recent_post.each_with_index do |post, index| %>
      <li class='post border1'>
        <%= render 'posts/post', post: post %>
   <%###################### DELETE POST BUTTON ########################%>
     <span>
      <%= render 'shared/delete_btn', object: post, path: user_post_path(@user, post) %>
    </span>
 <%###################### ADD COMMENT BUTTON ########################%>
         <div class=add_new_comm>
  <a href="<%= new_user_post_comment_path(current_user, post) %>" class="button button-wide">Add new comment</a>
</div>
      </li>
    <% end %>
  </ul>

  <% unless @user.posts.empty? %>
    <div class='see-all'><button><%= link_to 'See all posts', user_posts_path(@user) %></button></div>
  <% end %>
<%######################## END OF USER FORM ##########################%>
<%if false%>
<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>
<%end%>