config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[index new create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  after_save :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def initialize(attributes = {})
    super
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comment
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :select_user, only: %i[index show destroy]
  before_action :set_post, only: %i[show destroy]

  # GET /posts or /posts.json
  def index
    # select_user
    @posts = @user.posts.includes(:comments)
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    post = Post.new(post_params)
    post.author = current_user
    respond_to do |format|
      if post.save
        format.html { redirect_to "/users/#{current_user.id}", notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to "/users/#{current_user.id}", notice: 'Post was not successfully created.' }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    # select_user
    # # set_post
    # @comments = @post.comments.includes(:author)
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    # select_user
    # set_post
    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'Post deleted'
    else
      redirect_to user_posts_path(current_user), alert: 'Post not deleted'
    end
  end

  private

  def select_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path(current_user) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class = 'post_form'>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<div>

<% end %>

app/views/posts/_post.html.erb
<ul id="<%= dom_id post %>">

  <p>
    <strong>Author:</strong>
    <%= post.author.name %>
  </p>
  
 <li class="post_card">

   <div class="post_title">
   <p>
   
    <strong>Post:</strong>
    <%= link_to user_post_path(post.author, post) do %>
    <%= post.title %>
      <%end%>
   </p>
  </div>

 <div class="text">
  <p>
    <%= post.text %>
  </p>
 </div>

 <div class="like_comment">    
 <div>
   <p>
    <strong>Likes counter:</strong>
    <%= post.likes_counter %>
   </p>
  </div>
 <div>
   <p>
    <strong>Comments counter:</strong>
    <%= post.comments_counter %>
   </p>
  </div>
  </div>
</li>
</ul>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%if false%>
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>
<%end%>
<%############### NEW POST ###############%>

<section>
<%= render 'users/user', user: @user %> 
 <%= render 'shared/open_post_form', user: @user %>
  <ul class='comment_post'>
    <% if @user.posts.empty? %>
      <li class='post'>This user has no posts yet!</li>
    <% end %>

    <% @user.posts.each_with_index do |post, index| %>
      <li class='post'>
        <%= render 'post', post: post %>
    <%###################### DELETE POST BUTTON ########################%>
     <span>
      <%= render 'shared/delete_btn', object: post, path: user_post_path(@user, post) %>
    </span>
 <%###################### ADD COMMENT BUTTON ########################%>
 <div class=add_new_comm>
  <a href="<%= new_user_post_comment_path(current_user, post) %>" class="button button-wide">Add new comment</a>
</div>
         <%= render 'comments/comment', post: post, comment: post.recent_comment %>
      </li>
    <% end %>
  </ul>
  <div class="button_holder">
  <button>Pagination</button>
  <button><%= link_to 'Back', :back %></button>
</div>
</section>

app/views/posts/new.html.erb
<div class=post_new>
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", user_posts_path %>
</div>

</div>

app/views/posts/show.html.erb
<%= render @post %>

<%= render 'shared/enteract', user: @user, post: @post %>
<%= render 'comments/comment', post: @post, comment: @post.recent_comment%>

<%if false%>
<div class='show_post'>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
<%end%>